import prisma from '@/lib/prisma';
import { Prisma } from '@/../generated/prisma/client';
import 'dotenv/config'


const carData: Prisma.CarCreateInput[] = [
    {
        marca: "Toyota",
        modelo: "Corolla",
        anio: 2019,
        precio: 8700000,
        color: "Blanco",
        tipo_combustible: "Nafta",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "Sedán",
        motor: "1.8L 4 cilindros",
        patente: "AB123CD",
        tren_motriz: "Delantera",
        eficiencia_combustible: 14,
        color_interior: "Negro",
        descripcion: "Sedán confiable y eficiente, ideal para uso urbano con excelente reputación en durabilidad."
    },
    {
        marca: "Volkswagen",
        modelo: "Gol Trend",
        anio: 2019,
        precio: 5200000,
        color: "Gris",
        tipo_combustible: "Nafta",
        estado: "Usado",
        disponibilidad: "En stock",
        kilometraje: 64000,
        transmision: "Manual",
        tipo_carroceria: "Hatchback",
        motor: "1.6L 4 cilindros",
        patente: "AC456EF",
        tren_motriz: "Delantera",
        eficiencia_combustible: 13,
        color_interior: "Gris oscuro",
        descripcion: "Compacto confiable, económico y de fácil mantenimiento, ideal para ciudad."
    },
    {
        marca: "Ford",
        modelo: "Ranger XLT",
        anio: 2022,
        precio: 14500000,
        color: "Negro",
        tipo_combustible: "Diésel",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "Pickup",
        motor: "3.2L 5 cilindros",
        patente: "AE987GH",
        tren_motriz: "4x4",
        eficiencia_combustible: 9,
        color_interior: "Negro",
        descripcion: "Pickup robusta con excelente capacidad todoterreno y alto rendimiento diésel."
    },
    {
        marca: "Chevrolet",
        modelo: "Onix LT",
        anio: 2020,
        precio: 7100000,
        color: "Rojo",
        tipo_combustible: "Nafta",
        estado: "Usado",
        disponibilidad: "Vendido",
        kilometraje: 42000,
        transmision: "Manual",
        tipo_carroceria: "Sedán",
        motor: "1.2L 3 cilindros",
        patente: "AD654JK",
        tren_motriz: "Delantera",
        eficiencia_combustible: 15,
        color_interior: "Beige",
        descripcion: "Sedán moderno, eficiente y con buen equipamiento para uso diario."
    },
    {
        marca: "Renault",
        modelo: "Kangoo Express",
        anio: 2021,
        precio: 9400000,
        color: "Blanco",
        tipo_combustible: "Diésel",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Manual",
        tipo_carroceria: "Furgón",
        motor: "1.5L 4 cilindros",
        patente: "AF432PL",
        tren_motriz: "Delantera",
        eficiencia_combustible: 16,
        color_interior: "Negro",
        descripcion: "Vehículo utilitario eficiente y confiable, ideal para trabajo o reparto urbano."
    },
    {
        marca: "Peugeot",
        modelo: "208 Allure",
        anio: 2023,
        precio: 10500000,
        color: "Azul",
        tipo_combustible: "Nafta",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "Hatchback",
        motor: "1.6L 4 cilindros",
        patente: "AG321QP",
        tren_motriz: "Delantera",
        eficiencia_combustible: 15,
        color_interior: "Negro",
        descripcion: "Hatchback moderno, con diseño atractivo y gran eficiencia en consumo."
    },
    {
        marca: "Honda",
        modelo: "Civic EX",
        anio: 2022,
        precio: 13200000,
        color: "Gris Plata",
        tipo_combustible: "Nafta",
        estado: "Nuevo",
        disponibilidad: "Vendido",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "Sedán",
        motor: "2.0L 4 cilindros",
        patente: "AH554MN",
        tren_motriz: "Delantera",
        eficiencia_combustible: 13,
        color_interior: "Negro",
        descripcion: "Sedán elegante con gran confort, seguridad y excelente reputación de marca."
    },
    {
        marca: "Fiat",
        modelo: "Cronos Drive",
        anio: 2020,
        precio: 6500000,
        color: "Bordó",
        tipo_combustible: "Nafta",
        estado: "Usado",
        disponibilidad: "En stock",
        kilometraje: 38000,
        transmision: "Manual",
        tipo_carroceria: "Sedán",
        motor: "1.3L 4 cilindros",
        patente: "AI667RS",
        tren_motriz: "Delantera",
        eficiencia_combustible: 14,
        color_interior: "Gris oscuro",
        descripcion: "Sedán cómodo, económico y con buen espacio interior para la familia."
    },
    {
        marca: "Nissan",
        modelo: "Frontier LE",
        anio: 2021,
        precio: 13900000,
        color: "Negro",
        tipo_combustible: "Diésel",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "Pickup",
        motor: "2.3L Biturbo",
        patente: "AJ245TT",
        tren_motriz: "4x4",
        eficiencia_combustible: 10,
        color_interior: "Negro",
        descripcion: "Pickup potente y moderna con gran capacidad de carga y confort."
    },
    {
        marca: "Jeep",
        modelo: "Renegade Sport",
        anio: 2022,
        precio: 12500000,
        color: "Verde Militar",
        tipo_combustible: "Nafta",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "SUV",
        motor: "1.8L 4 cilindros",
        patente: "AK998UV",
        tren_motriz: "Delantera",
        eficiencia_combustible: 12,
        color_interior: "Negro",
        descripcion: "SUV compacto con diseño robusto y excelente desempeño urbano y en ruta."
    },
    {
        marca: "Toyota",
        modelo: "Hilux SRV",
        anio: 2023,
        precio: 18500000,
        color: "Gris Oscuro",
        tipo_combustible: "Diésel",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "Pickup",
        motor: "2.8L 4 cilindros",
        patente: "AL776QW",
        tren_motriz: "4x4",
        eficiencia_combustible: 10,
        color_interior: "Negro",
        descripcion: "Pickup líder en su segmento, robusta y confiable, ideal para trabajo o aventura."
    },
    {
        marca: "Volkswagen",
        modelo: "T-Cross Highline",
        anio: 2022,
        precio: 13800000,
        color: "Azul Marino",
        tipo_combustible: "Nafta",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "SUV",
        motor: "1.0L Turbo",
        patente: "AM220PL",
        tren_motriz: "Delantera",
        eficiencia_combustible: 14,
        color_interior: "Negro",
        descripcion: "SUV urbano moderno con gran tecnología y excelente eficiencia de consumo."
    },
    {
        marca: "Ford",
        modelo: "EcoSport SE",
        anio: 2018,
        precio: 6500000,
        color: "Blanco",
        tipo_combustible: "Nafta",
        estado: "Usado",
        disponibilidad: "En stock",
        kilometraje: 75000,
        transmision: "Manual",
        tipo_carroceria: "SUV",
        motor: "1.6L 4 cilindros",
        patente: "AN444RT",
        tren_motriz: "Delantera",
        eficiencia_combustible: 12,
        color_interior: "Gris",
        descripcion: "SUV compacto y versátil con buena altura al suelo y conducción cómoda."
    },
    {
        marca: "Chevrolet",
        modelo: "Tracker Premier",
        anio: 2023,
        precio: 15500000,
        color: "Rojo Fuego",
        tipo_combustible: "Nafta",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "SUV",
        motor: "1.2L Turbo",
        patente: "AO112GT",
        tren_motriz: "Delantera",
        eficiencia_combustible: 15,
        color_interior: "Negro",
        descripcion: "SUV moderno y eficiente con gran equipamiento tecnológico y de seguridad."
    },
    {
        marca: "Renault",
        modelo: "Sandero Stepway",
        anio: 2020,
        precio: 7800000,
        color: "Naranja",
        tipo_combustible: "Nafta",
        estado: "Usado",
        disponibilidad: "En stock",
        kilometraje: 45000,
        transmision: "Manual",
        tipo_carroceria: "Hatchback",
        motor: "1.6L 4 cilindros",
        patente: "AP335TR",
        tren_motriz: "Delantera",
        eficiencia_combustible: 13,
        color_interior: "Negro",
        descripcion: "Hatchback aventurero con buen despeje y confort para la ciudad o viajes."
    },
    {
        marca: "Peugeot",
        modelo: "2008 GT Line",
        anio: 2021,
        precio: 13800000,
        color: "Blanco Nacarado",
        tipo_combustible: "Nafta",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "SUV",
        motor: "1.2L Turbo",
        patente: "AQ568KL",
        tren_motriz: "Delantera",
        eficiencia_combustible: 15,
        color_interior: "Negro",
        descripcion: "SUV moderno y elegante con gran eficiencia y estilo europeo."
    },
    {
        marca: "Honda",
        modelo: "HR-V EXL",
        anio: 2023,
        precio: 16800000,
        color: "Gris Oscuro",
        tipo_combustible: "Nafta",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "CVT",
        tipo_carroceria: "SUV",
        motor: "1.8L 4 cilindros",
        patente: "AR899YU",
        tren_motriz: "Delantera",
        eficiencia_combustible: 14,
        color_interior: "Beige",
        descripcion: "SUV confiable y cómoda, con excelente calidad y bajo consumo."
    },
    {
        marca: "Fiat",
        modelo: "Toro Freedom",
        anio: 2022,
        precio: 15500000,
        color: "Gris Plata",
        tipo_combustible: "Diésel",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "Pickup",
        motor: "2.0L Multijet",
        patente: "AS712OP",
        tren_motriz: "4x4",
        eficiencia_combustible: 11,
        color_interior: "Negro",
        descripcion: "Pickup intermedia con buen confort y capacidad para trabajo o ciudad."
    },
    {
        marca: "Nissan",
        modelo: "Versa Advance",
        anio: 2021,
        precio: 9600000,
        color: "Azul Marino",
        tipo_combustible: "Nafta",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "Sedán",
        motor: "1.6L 4 cilindros",
        patente: "AT440LM",
        tren_motriz: "Delantera",
        eficiencia_combustible: 15,
        color_interior: "Negro",
        descripcion: "Sedán moderno y espacioso, ideal para uso familiar con bajo consumo."
    },
    {
        marca: "Jeep",
        modelo: "Compass Limited",
        anio: 2023,
        precio: 19800000,
        color: "Negro",
        tipo_combustible: "Nafta",
        estado: "Nuevo",
        disponibilidad: "En stock",
        kilometraje: 0,
        transmision: "Automática",
        tipo_carroceria: "SUV",
        motor: "1.3L Turbo",
        patente: "AU998XS",
        tren_motriz: "4x4",
        eficiencia_combustible: 12,
        color_interior: "Negro",
        descripcion: "SUV premium con tracción total y gran equipamiento de confort y seguridad."
    }
];

export async function main() {
    for (const u of carData) {
        await prisma.car.create({ data: u });
    }
}

main();